### ISSUE TITLE
Add Unity-like support for desktop actions on right-click

### ISSUE THREAD

**Issue by dannote** [gottcode/xfce4-whiskermenu-plugin#102]
Support for desktop actions (like Chromium's "Open New Incogito Window" or Nautilus' "Home Folder") is a required feature for a modern desktop environment.

**Comment by gottcode** [comment]
The Xfce library I use to parse the menu items (garcon) does not support desktop actions. I suggest you be less rude to the Xfce developers if you request they add support for them.
