### ISSUE TITLE
Add an option to change the Title font

### ISSUE THREAD

**Issue by Misko-2083** [gottcode/xfce4-whiskermenu-plugin#103]
Hi,
Can you add an option to change the Title font and color?
At the moment it's possible to use the <a href="https://developer.gnome.org/pygtk/stable/pango-markup-language.html"> pango markup language</a> to do this.
For example:
If I set the Title text to this:
`<span foreground="black" size="large">Menu</span>`
foreground will set the font color to black
size will set the font size to the absolute size "large"
Cheers

**Comment by gottcode** [comment]
I'm not aware of any Xfce panel plugin that lets you do that. It seems a bit much, sorry.

**Comment by Misko-2083** [comment]
Hm, strange
In the file ~/.config/xfce4/panel/whiskermenu-1.rc
This line seems to work
`button-title=<span foreground="black" size="large">Menu</span>`
Also you can see the screenshoot here:
<a href="http://i.imgur.com/thVMZ6T.png">http://i.imgur.com/thVMZ6T.png</a>

**Comment by gottcode** [comment]
I'm not denying that you can use pango markup, I'm saying I will not be adding options to control it. Every option adds more complexity, and I have to determine what I feel is appropriate to maintain.

**Comment by Misko-2083** [comment]
Okie Dokie. Sorry, I've misunderstood you. I just saw you will be adding transparency to the menu and suddenly I've lost interest in pango markup. Keep up the good work.
Cheers :)
