### ISSUE TITLE
CrossOver menu items do not appear

### ISSUE THREAD

**Issue by tliron** [gottcode/xfce4-whiskermenu-plugin#107]
Although they *do* appear in the Xfce Application Finder.

I deleted all the .desktop files and recreated them with CrossOver, but no success.

Any ideas how I can help debug this?

**Comment by gottcode** [comment]
Odd. Whisker Menu and the Application Finder both use garcon to create the list of menu items. Are the CrossOver items in a submenu? Are there any other launcher in the same submenu as them? I assume restarting the panel didn't show them.

**Comment by tliron** [comment]
Yes, they are in a submenu. I could send you my entire .desktop folder, maybe you could reproduce? Or can you suggest a way to debug garcon?

**Comment by gottcode** [comment]
Well, I'm not sure exactly how to debug Garcon, but your a copy of your applications folder would be helpful. Thanks!

**Comment by tliron** [comment]
Here it is: https://db.tt/Xj7jfzZF

**Comment by gottcode** [comment]
When I tested adding those folders, all of the entries were put underneath "Other" with no new categories or subcategories by both Whisker Menu and the application finder. Strange. What does the application finder look like for you?

**Comment by tliron** [comment]
In Application Finder, I have a category called "Windows Applications". But nothing in Whisker. I wonder if there are other configuration files I should be looking at?

**Comment by gottcode** [comment]
There are also XML files that can define the layout of the menu itself. You can see the whole set of files involved in making the menu here: http://standards.freedesktop.org/menu-spec/menu-spec-latest.html#paths

**Comment by tliron** [comment]
Hm. Let's make sure I'm using the right version: I'm in Xubuntu 14.04 64bit with the gottcode/gcppa PPA.

I'm curious as to why it appears as "Other" for you. There must be something wrong with the menu items in that they're not properly associated with a directory. But, on your setup it puts them in "Other" and in mine it doesn't even show them.

In Application Finder, do they appear in "Windows Applications" for you or in "Other"?

**Comment by gottcode** [comment]
They show up in "Other" in the Application Finder as well. It could be that there is a ```applications.menu``` file under ```~/.local/share/menus``` that it is using to create your menu structure that has the "Windows Applications" category. The menu items themselves do have a category, and there is a matching .directory file, but the menu is not adding them for some reason.

**Comment by tliron** [comment]
I do not have those files. Well, it's good to hear that Applicaion Finder and Whisker behave identically for you, even if there's something possibly wrong with these files. But it stands that on my machine they do not behave the same. The bug is serious, because it means I can't access these menu items at all from Whisker.

**Comment by gottcode** [comment]
Do the launchers show up in the "All" section? Can you search for them?

I have made a patched version of Whisker Menu that logs the process of loading the menu contents to a file named ```whiskermenu.log``` in your home directory, and I have uploaded it to http://beta.gottcode.org/xfce4-whiskermenu-plugin. If you would be willing to install that and send me a copy of the log file, that would be very much appreciated.

**Comment by tliron** [comment]
Thanks for rolling a DEB for me, but actually I am using Precise here and can't install this Utopic package due to its libstdc++6 (>= 4.9) requirement (Precise has 4.8.2).

The launcher don't show at all in Whisker Menu, not in "All" not the search bar. That's why I think it's a serious bug. On the same machine they do appear correctly in Application Finder in the group "Windows Applications". But oddly with your setup they do appear on both apps, but in the "Other" group.

**Comment by gottcode** [comment]
Unfortunately, without more data I really have no idea why Whisker Menu is not showing these items. I have built a 64-bit package for Precise and uploaded that as well. Thanks for your patience!

**Comment by tliron** [comment]
Unfortunately can't install the Precise package, either:

Dependency is not satisfiable: libxfce4util4 (>= 4.3.99.2)

**Comment by gottcode** [comment]
Okay, now that's strange (especially as libxfce4util4 is 4.8.2 in Precise). I built the package from inside of my Xubuntu 12.04.5 virtual machine, which should have the same packages as any actual install. How comfortable are you with compiling a version of Whisker Menu and installing manually?

**Comment by tliron** [comment]
Should be OK! Are there instructions somewhere? (Also, I suggest that this logging feature should be inside Whisker Menu permanently, possibly a config value.)

**Comment by tliron** [comment]
Ugh, excuse my idiocy. I meant "Trusty" above, not "Precise". Ubuntu 14.04.

**Comment by gottcode** [comment]
Ah, okay. No problem, I have made a 14.04 package. I have also uploaded the patch in case you need to build from source instead. The patch can be applied like a normal patch (```patch -p1 < whiskermenu_log.patch``` from the top of the source tree), and the build instructions are included in the INSTALL file in the source.

In the long term I will probably add a proper logging facility (optional, and disabled by default); this patch is really quite messy and hackish. Just enough to find out what is happening when it reads the different menu items.

**Comment by tliron** [comment]
Excellent! Here is the log: https://db.tt/3SJtkChG

**Comment by gottcode** [comment]
Thanks for the log! It shows that Whisker Menu sees the items as belonging in "Other", and that they are hidden. It doesn't see a "Windows Programs" category at all. Whisker Menu loads the menu items in a similar manner to the default applications menu applet, but not to the application finder. Do these menu items show up the with the default applications menu?

**Comment by tliron** [comment]
It does not appear in the default applications menu, you are right.

And yes, I do have that file! I added it to the zip: https://db.tt/Xj7jfzZF

Where does this file come from, how is it generated, and which apps use it? I don't see any mention of hidden menus, but could it be that my menus aren't there? If I delete it would it just be regenerated?

**Comment by tliron** [comment]
OK, I can confirm that deleting this file and restarting Whisker causes it to be regenrated and the problems I had disappeared.

I guess the question remains how I got into this state exactly. I guess the Application Finder doesn't have this problem because it's not actually a "menu" and thus doesn't even read this file.

My thought is that Whisker Menu, in its "All" category and also in search, should act like Application Finder and least let you execute anything you have, even if it's hidden. What do you think?

**Comment by gottcode** [comment]
> Where does this file come from, how is it generated, and which apps use it? I don't see any mention of hidden menus, but could it be that my menus aren't there? If I delete it would it just be regenerated?

The file is created by menu editors, possibly even by CrossOver. Any program that wants to modify your menu structure will probably create it. The file is used by programs that follow the [desktop menu specification](http://standards.freedesktop.org/menu-spec/menu-spec-latest.html) to lay out the menu. And the file will probably be regenerated by whatever process created it in the first place.

> I guess the question remains how I got into this state exactly. I guess the Application Finder doesn't have this problem because it's not actually a "menu" and thus doesn't even read this file.

Actually, the Application Finder does load this file. It just uses a different set of functions from garcon for iterating over the items in the file.

> My thought is that Whisker Menu, in its "All" category and also in search, should act like Application Finder and least let you execute anything you have, even if it's hidden. What do you think?

Unfortunately, it's not that simple. There are legitimate reasons why some launchers are hidden (for instance, some programs install multiple launchers for a single application, but use them in right-click menus).

The basic issue is that garcon has two different ways of iterating over the menu elements, and they don't show the same set of items. I have to use the same set of functions as the applications menu applet to allow users the option of showing subcategories and separators.

> OK, I can confirm that deleting this file and restarting Whisker causes it to be regenrated and the problems I had disappeared.

I'm glad to hear that! As this is due to a difference in how garcon treats the menu structure, and the applications menu was affected in the same way, I am considering this an upstream issue.

**Comment by kernc** [comment]
> I am considering this an upstream issue.

Seemingly understanding the problem well, will you report it upstream? :)

**Comment by tliron** [comment]
I'd say there are two upstreams:

Xfce project: The issue is that Application Finder and Application Menu behave differently and may show a different selection of items. This is confusing, and indeed has led to Whisker Menu rather arbitrarily deciding to model itself over one of them. I'm sure a lot of other alternate launchers for Xfce had the same problem.

Or, (and this is something gottcode would know) perhaps the alternate garcon APIs should behave in a different way here in order to guarantee consistency. And there's probably a better way to report that there is a validation error of some sort. (None of the tools I've been using to try to debug this -- four different ones -- reported any error.)

MenuLibre: I'm pretty sure I was using this to edit that xfce-applications.menu. I definitely used it to try to find what the problem was. But it didn't show any problem with this menu -- nothing was "hidden" there, though it was obviously hidden in Whisker Menu and Application Menu. I think if there's a tool that should be expected to validate all these files, it's this one. The problematic ones should appear bright red!

**Comment by gottcode** [comment]
> Seemingly understanding the problem well, will you report it upstream?

Yes, but first I need time to create an example of the difference in menu item results between using ```garcon_menu_get_elements()``` (Whisker Menu and the default applications menu) and ```garcon_menu_get_item_pool()``` (the application finder).

> Or, (and this is something gottcode would know) perhaps the alternate garcon APIs should behave in a different way here in order to guarantee consistency. And there's probably a better way to report that there is a validation error of some sort. (None of the tools I've been using to try to debug this -- four different ones -- reported any error.)

The issue is caused by how ```garcon_menu_get_item_pool()``` processes the menu structure. The other tools wouldn't show a problem.

> MenuLibre: I'm pretty sure I was using this to edit that xfce-applications.menu. I definitely used it to try to find what the problem was. But it didn't show any problem with this menu -- nothing was "hidden" there, though it was obviously hidden in Whisker Menu and Application Menu. I think if there's a tool that should be expected to validate all these files, it's this one. The problematic ones should appear bright red!

Hidden items aren't an error, not exactly. You can have hidden items, and you can set them to be hidden yourself. I agree that MenuLibre should show hidden items differently. Alacarte showed them in italics, perhaps the maintainers of MenuLibre would be willing to do the same?
